######################################################################
# Automatically generated by qmake (3.1) Thu Jul 17 12:31:14 2025
######################################################################
QT       += core gui network charts sql webenginewidgets
TEMPLATE = app
TARGET = AiotClient_tab5
INCLUDEPATH += .
INCLUDEPATH += /usr/local/include/opencv4
LIBS += `pkg-config opencv4 --cflags --libs`

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += keyboard.h \
           ledkeydev.h \
           mainwidget.h \
           socketclient.h \
           tab1devcontrol.h \
           tab2socketclient.h \
           tab3controlpannel.h \
           tab4sensorchart.h \
           tab5sensordatabase.h \
           tab6webcamera.h \
           tab7camviewthread.h \
           webcamthread.h
FORMS += keyboard.ui \
         mainwidget.ui \
         tab1devcontrol.ui \
         tab2socketclient.ui \
         tab3controlpannel.ui \
         tab4sensorchart.ui \
         tab5sensordatabase.ui \
         tab6webcamera.ui \
         tab7camviewthread.ui
SOURCES += keyboard.cpp \
           ledkeydev.cpp \
           main.cpp \
           mainwidget.cpp \
           socketclient.cpp \
           tab1devcontrol.cpp \
           tab2socketclient.cpp \
           tab3controlpannel.cpp \
           tab4sensorchart.cpp \
           tab5sensordatabase.cpp \
           tab6webcamera.cpp \
           tab7camviewthread.cpp \
           webcamthread.cpp
RESOURCES += Images.qrc
